export { Home as PageHome } from "./Home"
export { Layout as PageLayout } from "./Layout"
export { Cadastrar as PageCadastrar } from "./Cadastrar"
export { Login as PageLogin } from "./Login"
export { Adm as PageAdm } from "./Adm"
export { Effects as PageEffects } from "./Effects"
export { Instruments as PageInstruments} from "./Instruments"
export { AandC as PageAandC } from "./Amps&Cabinets"